'use client';

import Link from "next/link";
import { ArrowLeft, Gavel } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-bg text-fg">
      <div className="absolute inset-0 grid-canvas opacity-40 pointer-events-none" />

      <header className="border-b border-border bg-bg/80 backdrop-blur-md sticky top-0 z-50">
        <div className="mx-auto max-w-6xl px-5 sm:px-8 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="h-7 w-7 rounded-md bg-accent/20 border border-accent/30 grid place-items-center">
              <span className="text-accent text-sm font-semibold">◈</span>
            </div>
            <span className="font-semibold tracking-tight">OnboardGhost</span>
          </Link>
          <Link href="/" className="text-sm text-muted hover:text-fg transition-colors flex items-center gap-1.5">
            <ArrowLeft size={14} /> Back to home
          </Link>
        </div>
      </header>

      <main className="relative mx-auto max-w-3xl px-5 sm:px-8 py-16 sm:py-24">
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 text-accent bg-accent/10 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider mb-6">
            <Gavel size={14} /> Terms of Service
          </div>
          <h1 className="font-serif text-4xl sm:text-5xl mb-4">Terms & Conditions</h1>
          <p className="text-muted">Last updated: April 20, 2026</p>
        </div>

        <div className="prose prose-invert max-w-none space-y-10">
          <section>
            <h2 className="text-2xl font-serif text-fg mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted leading-relaxed">
              By using OnboardGhost, you agree to these terms. If you do not agree, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-serif text-fg mb-4">2. AI-Generated Content</h2>
            <p className="text-muted leading-relaxed">
              The roadmaps, analysis, and Mentor responses provided by OnboardGhost are generated by 
              Artificial Intelligence. While we strive for accuracy, AI can make mistakes. You are 
              responsible for verifying the technical advice provided before applying it to production 
              environments.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-serif text-fg mb-4">3. Use of GitHub Data</h2>
            <p className="text-muted leading-relaxed">
              When you analyze a repository, you grant us permission to access its metadata and files 
              temporarily for analysis purposes. You must have the necessary rights to analyze the 
              repositories you provide.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-serif text-fg mb-4">4. Limitations of Liability</h2>
            <p className="text-muted leading-relaxed">
              OnboardGhost is provided "as is" without any warranties. We are not liable for any 
              damages resulting from the use or inability to use our services, including data loss 
              or incorrect technical guidance.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-serif text-fg mb-4">5. Termination</h2>
            <p className="text-muted leading-relaxed">
              We reserve the right to suspend or terminate access to OnboardGhost for users who 
              violate these terms or engage in abusive behavior towards our systems.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
